[tool.black]
target-version = ['py39']

[tool.isort]
profile = "black"
add_imports = "from __future__ import annotations"

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
strict = true
warn_unused_ignores = true
